In [1]:
import numpy as np
import pandas as pd
import math

## Read this cell before your work on this exam.
1. Do not import any other packages. You only can use three packages imported in the first cell.
2. Due time of this exam is 2pm on 10/31/2017. Any submission after this time is not acceptable. Please submit your .ipynb file for question 1-3 through Canvas on time.
3. Please write all necessary steps and final answer of question 4 and brint it to me in next Tuesday's class.
4. Please work on this exam by yourself. Do not discuss and share anything with other students. Email me if you have any questions.

## Question1 (25 pts)
### Please refer lab3 to answer this question.
For the following vectors, x and y, calculate the indicated similarity or distance measures. Print out the results.

(a) x = (1,1,1,1), y = (2,2,2,2)  L1 distance, L2 distance

(b) x = (2,-1,0,2,0,-3), y = (-1,1,-1,0,0,-1) Linfinity distance, correlation coefficient

(c) x = (0,-1,0,1), y = (1,0,-1,0) correlation coefficient

In [ ]:
# Your code goes here

## Question2 (25 pts)
### Pelase refer lab6 to answer this question.
Consider the training example in following table for a binary decision tree problem.

(a) Computer gini index for the overall collection of training examples.

(b) Based on gini index, which attribute is better, Gender, Car Type, or Shirt Size?

(c) Computer gini index for the Customer ID attribute. Does this attribute have lowest gini index comparing with other three attrabutes? If yes, explain we should not choose Customer ID to split data.

In [18]:
df = pd.DataFrame({"Customer ID" : [i for i in range(1,21)],
                   "Gender" : map(lambda x: "M" if x==1 else "F", [1,1,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2,2,2]),
                   "Car Type" : map(lambda x: "Family" if x==1 else ("Sports" if x==2 else "Luxury"), 
                                    [1,2,2,2,2,2,2,2,2,3,1,1,1,3,3,3,3,3,3,3]),
                   "Shirt Size" : ["Small","Medium","Medium","Large","Extra Large","Extra Large","Small","Small",
                                   "Medium","Large","Large","Extra Large","Medium","Extra Large","Small","Small",
                                   "Medium","Medium","Medium","Large"],
                   "Class": map(lambda x: "C0" if x<10 else "C1", [i for i in range(20)])})
df = df[["Customer ID","Gender","Car Type","Shirt Size", "Class"]]

df

    Customer ID Gender Car Type   Shirt Size Class
0             1      M   Family        Small    C0
1             2      M   Sports       Medium    C0
2             3      M   Sports       Medium    C0
3             4      M   Sports        Large    C0
4             5      M   Sports  Extra Large    C0
5             6      M   Sports  Extra Large    C0
6             7      F   Sports        Small    C0
7             8      F   Sports        Small    C0
8             9      F   Sports       Medium    C0
9            10      F   Luxury        Large    C0
10           11      M   Family        Large    C1
11           12      M   Family  Extra Large    C1
12           13      M   Family       Medium    C1
13           14      M   Luxury  Extra Large    C1
14           15      F   Luxury        Small    C1
15           16      F   Luxury        Small    C1
16           17      F   Luxury       Medium    C1
17           18      F   Luxury       Medium    C1
18           19      F   Luxury       Medium    C1
19           20      F   Luxury        Large    C1

In [ ]:
# Your code goes here:

## Question 3 (25 pts)
### Please refer lab7 to answer this question.

<img src="Q3.png" alt="Drawing" style="width: 550px;"/>

(a) Which attribute, X, Y, Z, is best feature at the root of decision tree based on classification error?

(b) Build a two-level decision tree.

In [ ]:
# Your code goes here:

## Question 4 (25 pts)

### I will distribute paper of question 4 in class. This question does not require you to write code.